{
 "title": "DarkoWeb3StorgePerf",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_MIMIR", "label": "mimir", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Distribution metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Notes\n- IPFS server with content is in Ljubljana. Uploaded content is pinned\n- concerning secondary downloads only bee-3.dev server has some extra caching. (65.108.101.3\n65.108.104.135). The rest is just bee.\n- IPFS gateway servers used are: \"ipfs.io\", \"w3s.link\", \"ipfs.eth.aragon.network\", \"nftstorage.link\", \"cloudflare-ipfs.com\"\n- size is in kilobytes values in seconds\n- source https://github.com/darkobas2/util_web3_storageperf"
   }
  },
  {
   "title": "Distribution IPFS",
   "type": "histogram",
   "description": "Time it takes from when data was uploaded to when it was first downloaded. ie. distribution time\ny - number of concluded tests\nx - time those tests were concluded in",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "util_web3_storage_download_time{storage=~\"Ipfs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution SWARM",
   "type": "histogram",
   "description": "Time it takes from when data was uploaded to when it was first downloaded. ie. distribution time\ny - number of concluded tests\nx - time those tests were concluded in",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "util_web3_storage_download_time{storage=~\"Swarm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean time/size",
   "type": "barchart",
   "description": "compare mean times\ny axis is time in seconds\nx axis is grouped by tested data in kilobytes and storage",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "util_web3_storage_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max time/size",
   "type": "barchart",
   "description": "compare mean times\ny axis is time in seconds\nx axis is grouped by tested data in kilobytes and storage",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "util_web3_storage_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min time/size",
   "type": "barchart",
   "description": "compare mean times\ny axis is time in seconds\nx axis is grouped by tested data in kilobytes and storage",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "util_web3_storage_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution Times",
   "type": "geomap",
   "description": "How long it takes after the data was uploaded that it can be discovered and downloaded from a random node",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "util_web3_storage_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution Times",
   "type": "table",
   "description": "How long it takes after the data was uploaded that it can be discovered and downloaded from a random node",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "util_web3_storage_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution Times SHORT",
   "type": "table",
   "description": "How long it takes after the data was uploaded that it can be discovered and downloaded from a random node",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "util_web3_storage_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count SHA mismatches (Failed Download)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(util_web3_storage_sha_fail_total[$__rate_interval])",
     "legendFormat": "{{auto}}"
    }
   ]
  },
  { "title": "Gateway metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Existing Downloads IPFS",
   "type": "histogram",
   "description": "Time it takes from when data was uploaded to when it was first downloaded. ie. distribution time\ny - number of concluded tests\nx - time those tests were concluded in",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "util_web3_storage_repeat_download_time{storage=~\"Ipfs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Existing Downloads Swarm",
   "type": "histogram",
   "description": "Time it takes from when data was uploaded to when it was first downloaded. ie. distribution time\ny - number of concluded tests\nx - time those tests were concluded in",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "util_web3_storage_repeat_download_time{storage=~\"Swarm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Existing data DL Mean time/size",
   "type": "barchart",
   "description": "compare mean times\ny axis is time in seconds\nx axis is grouped by tested data in kilobytes and storage",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "util_web3_storage_repeat_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Existing data DL Min time/size",
   "type": "barchart",
   "description": "compare mean times\ny axis is time in seconds\nx axis is grouped by tested data in kilobytes and storage",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "util_web3_storage_repeat_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Existing data DL Max time/size",
   "type": "barchart",
   "description": "compare mean times\ny axis is time in seconds\nx axis is grouped by tested data in kilobytes and storage",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "util_web3_storage_repeat_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Existing Downloads Times",
   "type": "geomap",
   "description": "How long it takes after the data was uploaded that it can be discovered and downloaded from a random node",
   "gridPos": { "h": 12, "w": 10, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "util_web3_storage_repeat_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Existing Downloads Times",
   "type": "table",
   "description": "How long it takes after the data was uploaded that it can be discovered and downloaded from a random node",
   "gridPos": { "h": 12, "w": 14, "x": 10, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "util_web3_storage_repeat_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Existing DL SHORT",
   "type": "table",
   "description": "How long it takes after the data was uploaded that it can be discovered and downloaded from a random node",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "util_web3_storage_repeat_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count SHA mismatches (Failed Download)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(util_web3_storage_repeat_sha_fail_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Download metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 151 },
   "options": {
    "content": "# Notes\n- There are some ?anomalies? (or is it ?) in ipfs fetch... so for the sake of prettier graphs we filter out any values above 1000s\n- IPFS server with content is in Ljubljana. all Uploads are pinned\n- IPFS downloads using ipget https://github.com/ipfs/ipget\n- size is in kilobytes values in seconds\n- source https://github.com/darkobas2/util_web3_storageperf"
   }
  },
  {
   "title": "Existing Downloads IPFS",
   "type": "histogram",
   "description": "y - number of concluded tests\nx - time those tests were concluded in\nWe are filtering out all values above 1000 seconds!!!",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "util_web3_storage_old_download_time{storage=~\"Ipfs\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Existing Downloads SWARM",
   "type": "histogram",
   "description": "Time it takes from when data was uploaded to when it was first downloaded. ie. distribution time\ny - number of concluded tests\nx - time those tests were concluded in",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "util_web3_storage_old_download_time{storage=~\"Swarm\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Old data downloads Mean time/size",
   "type": "barchart",
   "description": "compare mean times\ny axis is time in seconds\nx axis is grouped by tested data in kilobytes and storage\nWe are filtering out all values above 1000 seconds!!!",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 163 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "util_web3_storage_old_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Old data downloads Max time/size",
   "type": "barchart",
   "description": "compare mean times\ny axis is time in seconds\nWe are filtering out all values above 1000 seconds!!!\nx axis is grouped by tested data in kilobytes and storage",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "util_web3_storage_old_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Old data downloads Min time/size",
   "type": "barchart",
   "description": "compare mean times\ny axis is time in seconds\nWe are filtering out all values above 1000 seconds!!!\nx axis is grouped by tested data in kilobytes and storage",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "util_web3_storage_old_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Old data download times",
   "type": "geomap",
   "description": "How long it takes after the data was uploaded that it can be discovered and downloaded from a random node",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 190 },
   "targets": [
    {
     "expr": "util_web3_storage_old_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Old data download table",
   "type": "table",
   "description": "How long it takes after the data was uploaded that it can be discovered and downloaded from a random node",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "util_web3_storage_old_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Old data downloads Times SHORT",
   "type": "table",
   "description": "How long it takes after the data was uploaded that it can be discovered and downloaded from a random node",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 207 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "util_web3_storage_old_download_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count SHA mismatches (Failed Download)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(size, storage) (util_web3_storage_old_sha_fail_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}