library(jsonlite) # Converting JSON files to data frames
library(tidyverse) # Efficient data manipulation and plotting
library(broom) # Tabular formatting of statistical model outputs
library(ggfortify) # Diagnostic plots for linear statistical models



# Load server ip addresses from a designated config file, arranged in
# a table. The table will have three columns: `server` (whether we
# are storing the ip of Server 1, Server 2, etc.), `platform` (Swarm,
# IPFS, or Arweave), and `ip` (the actual ip address).
serversFromConfig <- function(configFile = "../config.json") {
  # Read JSON data from file and convert to data frame:
  fromJSON(configFile) |>
    # Convert data frame to a tibble:
    as_tibble() |>
    # Choose only the three columns pertaining to the servers:
    select(contains("dl")) |>
    # Label them as "Server 1", "Server 2", ...:
    mutate(server = str_c("Server ", 1:3), .before = 1) |>
    # Simplify column names by dropping the "_dl_servers" suffix:
    rename_with(\(x) str_remove(x, "_dl_servers"), !server) |>
    # Tidy the data:
    pivot_longer(!server, names_to = "platform", values_to = "ip") |>
    # Change storage platform names to reflect proper capitalization:
    mutate(platform = case_match(
      platform,
      "swarm" ~ "Swarm",
      "ipfs"  ~ "IPFS",
      "arw"   ~ "Arweave"
    ))
}


# Load result data of the benchmarking experiment from a JSON file,
# and arrange them in a rectangular table:
dataFromJsonRaw <- function(jsonFile = "../results-new.json") {
  # Read JSON data file:
  fromJSON(jsonFile) |>
    # Convert to a tibble:
    as_tibble() |>
    # Unpack the nested `tests` column:
    unnest(tests) |>
    # And then the sub-nested `results` column:
    unnest(results) |>
    # Give new names to some of the columns:
    rename(time_sec = download_time_seconds,
           replicate = ref,
           platform = storage)
}


# Take the raw data generated by dataFromJsonRaw(), and tidy it up:
dataFromJson <- function(rawTable) {
  # Start from the tibble generated by dataFromJsonRaw():
  rawTable |>
    # Convert the JSON true/false into R's native TRUE and FALSE:
    mutate(sha256_match = (sha256_match == "true")) |>
    # File size is a character string; convert to integer:
    mutate(size_kb = as.integer(size)) |>
    # Remove unnecessary columns:
    select(!size & !server & !timestamp) |>
    # Properly capitalize IPFS in the `platform` column - important
    # for matching with the server ip data from serversFromConfig():
    mutate(platform = ifelse(platform == "Ipfs","IPFS",platform)) |>
    # Now join table with server ip info, so we'll know which ip
    # is Server 1, which is Server 2, etc.:
    left_join(serversFromConfig(), by = join_by(platform, ip)) |>
    # Rearrange the order of the columns:
    relocate(size_kb, server, time_sec, attempts, sha256_match,
             .after = platform)
}



dataFromJsonRaw("../results-new.json")
